// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_KRa9_HXk7zZOP0af_2TXXHeN9dD8Cc',
    appId: '1:11329512160:web:186a7ee8fa79beb242a685',
    messagingSenderId: '11329512160',
    projectId: 'notemanagement-task',
    authDomain: 'notemanagement-task.firebaseapp.com',
    storageBucket: 'notemanagement-task.firebasestorage.app',
    measurementId: 'G-93NY5BTKKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTeekisI4v7L8xpIR0U6LkLdheWtRiXY',
    appId: '1:11329512160:android:866bf63087f9e66b42a685',
    messagingSenderId: '11329512160',
    projectId: 'notemanagement-task',
    storageBucket: 'notemanagement-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06y47wNaaEKsYLKFRp7uwICIloiGzz30',
    appId: '1:11329512160:ios:d07350f19ab796af42a685',
    messagingSenderId: '11329512160',
    projectId: 'notemanagement-task',
    storageBucket: 'notemanagement-task.firebasestorage.app',
    iosBundleId: 'com.ostad.noteapp.noteApp',
  );
}
